name: CI/CD workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout the master
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ahmedbaz/demo-service
          tags: 1.1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: [ aws-ec2 ]
    steps:
      - name: Pull Image from docker hub
        run: docker pull ahmedbaz/demo-service:latest
      - name: Delete old container
        run: docker rm -f demo-service
      - name: Run docker container
        run: docker run -d -p 2222:2222 --name demo-service ahmedbaz/demo-service