name: CI/CD workflow to build/test and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the master
        uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: build with Maven
        run: mvn clean install -Dmaven.test.skip=true
  do_test:
    needs: build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: demo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        volumes:
          - postgres_dev:/var/lib/postgresql/data
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: run the maven verify phase
        run: mvn verify
  prepare_image:
    needs: do_test
    runs-on: ubuntu-latest
    steps:
      - name: checkout the master
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: build with maven
        run: mvn clean install -Dmaven.test.skip=true
      - name: build and push the image to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ahmedbaz/demo-service
          tags: pilot
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: prepare_image
    runs-on: [ self-hosted ]
    steps:
      - name: pull image from docker hub
        run: docker pull ahmedbaz/demo-service:pilot
      - name: Delete old container
        run: docker rm -f demo-service-pilot
      - name: Run docker container
        run: docker run -d -p 8080:2222 --name demo-service-pilot ahmedbaz/demo-service:pilot